//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string AttenddanceStatus { get; set; }
        public Nullable<System.DateTime> AttendanceMarkAt { get; set; }
        public Nullable<int> AttendanceMarkBy { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
        public virtual Student Student { get; set; }
    }
}
