//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.BatchBooks = new HashSet<BatchBook>();
            this.BatchTeacherDetails = new HashSet<BatchTeacherDetail>();
            this.StudentBatchTransfers = new HashSet<StudentBatchTransfer>();
            this.StudentBatches = new HashSet<StudentBatch>();
        }
    
        public string BatchCode { get; set; }
        public Nullable<int> BatchTiming { get; set; }
        public Nullable<System.DateTime> BatchStartDate { get; set; }
        public string BatchStatus { get; set; }
        public Nullable<int> BatchBy { get; set; }
        public string Notes { get; set; }
        public string BatchDays { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Day Day1 { get; set; }
        public virtual ICollection<BatchBook> BatchBooks { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BatchTeacherDetail> BatchTeacherDetails { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual ICollection<StudentBatchTransfer> StudentBatchTransfers { get; set; }
        public virtual ICollection<StudentBatch> StudentBatches { get; set; }
    }
}
