//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BatchBooks = new HashSet<BatchBook>();
        }
    
        public int Id { get; set; }
        public string BookName { get; set; }
        public Nullable<int> SemesterId { get; set; }
    
        public virtual ICollection<BatchBook> BatchBooks { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
