//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public CourseDetail()
        {
            this.Semesters = new HashSet<Semester>();
            this.Students = new HashSet<Student>();
        }
    
        public int CourseDetail1 { get; set; }
        public string CourseDetailName { get; set; }
        public Nullable<int> CourseDetailTree { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Cours Cours1 { get; set; }
        public virtual ICollection<Semester> Semesters { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
