//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseDetails = new HashSet<CourseDetail>();
            this.CourseDetails1 = new HashSet<CourseDetail>();
        }
    
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string CourseAbbreviation { get; set; }
        public string CourseStatus { get; set; }
    
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
        public virtual ICollection<CourseDetail> CourseDetails1 { get; set; }
    }
}
