//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BatchTeacherDetails = new HashSet<BatchTeacherDetail>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string ContactNo { get; set; }
        public string EmployeeStatus { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<BatchTeacherDetail> BatchTeacherDetails { get; set; }
    }
}
