//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public string SemesterName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> SemesterSession { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual CourseDetail CourseDetail { get; set; }
    }
}
