//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotAssign
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public string SlotDays { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string TaskStatus { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Day Day1 { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual TimeSlot TimeSlot1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
