//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBatch
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string BatchCode { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string BatchStatus { get; set; }
        public Nullable<int> ChangesDoneBy { get; set; }
        public string Notes { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual User User { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User1 { get; set; }
    }
}
