//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.StudentBatches = new HashSet<StudentBatch>();
            this.StudentBatchTransfers = new HashSet<StudentBatchTransfer>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string NICNumber { get; set; }
        public Nullable<int> StudentCourse { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public Nullable<int> ChangesDoneBy { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual CourseDetail CourseDetail { get; set; }
        public virtual ICollection<StudentBatch> StudentBatches { get; set; }
        public virtual ICollection<StudentBatchTransfer> StudentBatchTransfers { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
