//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Batches = new HashSet<Batch>();
            this.BatchBooks = new HashSet<BatchBook>();
            this.BatchTeacherDetails = new HashSet<BatchTeacherDetail>();
            this.LoginHistories = new HashSet<LoginHistory>();
            this.SlotAssigns = new HashSet<SlotAssign>();
            this.SlotAssigns1 = new HashSet<SlotAssign>();
            this.StudentBatches = new HashSet<StudentBatch>();
            this.StudentBatches1 = new HashSet<StudentBatch>();
            this.StudentBatchTransfers = new HashSet<StudentBatchTransfer>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string Userstatus { get; set; }
        public Nullable<System.DateTime> UserCreatedOn { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<BatchBook> BatchBooks { get; set; }
        public virtual ICollection<BatchTeacherDetail> BatchTeacherDetails { get; set; }
        public virtual ICollection<LoginHistory> LoginHistories { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SlotAssign> SlotAssigns { get; set; }
        public virtual ICollection<SlotAssign> SlotAssigns1 { get; set; }
        public virtual ICollection<StudentBatch> StudentBatches { get; set; }
        public virtual ICollection<StudentBatch> StudentBatches1 { get; set; }
        public virtual ICollection<StudentBatchTransfer> StudentBatchTransfers { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
