//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherStatus { get; set; }
        public Nullable<System.DateTime> VoucherDistributedAt { get; set; }
        public Nullable<int> VoucherDistributedBy { get; set; }
        public string Notes { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
